from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from app.business.models.subtitle import SubtitleSegment, SubtitleTranscript


class SubtitleSegmentResponse(BaseModel):
    text: str = Field(..., description="Subtitle text.")
    start: float = Field(..., ge=0, description="Start time in seconds.")
    duration: float = Field(..., ge=0, description="Duration in seconds.")

    @classmethod
    def from_domain(cls, segment: SubtitleSegment) -> "SubtitleSegmentResponse":
        return cls(
            text=segment.text,
            start=segment.start,
            duration=segment.duration,
        )


class SubtitleTranscriptResponse(BaseModel):
    model_config = ConfigDict(frozen=True)

    source: str = Field(..., description="Transcript source identifier.")
    video_id: str = Field(..., description="Provider specific video id.")
    language: str = Field(..., description="Human readable language name.")
    language_code: str = Field(..., description="Language code, for example en.")
    is_generated: bool = Field(
        ...,
        description="Whether the transcript was auto-generated by the provider.",
    )
    segments: list[SubtitleSegmentResponse] = Field(
        ...,
        description="Normalized subtitle segments.",
    )

    @classmethod
    def from_domain(cls, transcript: SubtitleTranscript) -> "SubtitleTranscriptResponse":
        return cls(
            source=transcript.source,
            video_id=transcript.video_id,
            language=transcript.language,
            language_code=transcript.language_code,
            is_generated=transcript.is_generated,
            segments=[
                SubtitleSegmentResponse.from_domain(segment)
                for segment in transcript.segments
            ],
        )

